- name: install nodejs prerequisites
  apt:
    name:
      - apt-transport-https
      - gcc
      - g++
      - make
    state: present

- name: add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version_major }}.x {{ ansible_lsb.codename }} main"
    state: present
    update_cache: yes

- name: install nodejs
  apt:
    name: nodejs
    state: present

# - name: install npm packages
#   command: "npm install -g {{ item }}"
#   with_items:
#     - "typescript"
#     - "@vue/cli"
 
