- name: make sure virutenvs directory exist
  file:
    path: "{{ virtualenvs_path }}"
    state: directory
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"

- name: install virualenv and wrapper
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
      - ansible-lint
      - hvac # ansible hashi corp vault lookup
      - jinja2
      - pyyaml
      - black # python formatting
      # python linters or syntax checkers used by emacs
      - flake8
      - pylint
      - mypy
      - pyright
      # data
      - ipython
      # emacs auto python auto import
      - importmagic
      - epc
  become: true
  become_user: "{{ workstation_user }}"
